### ISSUE TITLE
[Bug Report] - 

### ISSUE THREAD

**Issue by magcicada** [OneLemonyBoi/MiniUtilities#128]
The newest build jar can't work with [Liberica OpenJDK](https://bell-sw.com/pages/downloads/#/java-11-lts) of BellSoft, it will carsh at game launch.
This is the log of launch then crash:
[latest.log](https://github.com/OneLemonyBoi/MiniUtilities/files/8403841/latest.log)
MiniUtilities version: https://github.com/OneLemonyBoi/MiniUtilities/actions/runs/2024690138
Minecraft version: 1.16.5
Forge version: 36.2.33

**Comment by OneLemonyBoi** [comment]
Forge issue, not mine.
`[22:35:32] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoSuchMethodError: sun.security.util.ManifestEntryVerifier.<init>(Ljava/util/jar/Manifest;)V
[22:35:32] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.SecureJarHandler.createCodeSource(SecureJarHandler.java:66)
[22:35:32] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:275)
`
