### ISSUE TITLE
Error with Corail Tombstone mod

### ISSUE THREAD

**Issue by jahirtrap** [OneLemonyBoi/MiniUtilities#29]
When using the miniutilities mod together with [Tombstone](https://www.curseforge.com/minecraft/mc-mods/corail-tombstone/files/3308280) the tomb is not generated (all inventory disappears) and the message appears: "An unexpected error occurred trying to execute that command"

Mod list: tombstone, miniutilities, lemonlib, curios

Forge version: 1.16.5-36.1.18
Tombstone version: 6.3.6
miniutilities version: 1.1.1
lemonlib version: 1.3.3
Curios version: 1.16.5-4.0.5.1

![2021-05-14_08 14 27](https://user-images.githubusercontent.com/75038202/118276299-1cb5d880-b48d-11eb-80cd-da810e1cfa71.png)

**Comment by OneLemonyBoi** [comment]
Do you have the logs?

**Comment by jahirtrap** [comment]
[crash-2021-05-13_23.04.45-server.txt](https://github.com/OneLemonyBoi/MiniUtilities/files/6479861/crash-2021-05-13_23.04.45-server.txt)
-------------------------------------------------------------------------------------------------------------------------------------------
[13may2021 23:04:45.663] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$2966/988902163@58891963
		2: net.minecraftforge.eventbus.EventBus$$Lambda$2966/988902163@9c3938d
		3: net.minecraftforge.eventbus.EventBus$$Lambda$2966/988902163@60474307
		4: LOW
		5: ASM: se.mickelus.tetra.effect.ItemEffectHandler@33f649ca onExperienceDrop(Lnet/minecraftforge/event/entity/living/LivingExperienceDropEvent;)V
		6: LOWEST
		7: ASM: class ovh.corail.tombstone.event.EventHandler onLivingExperienceDrop(Lnet/minecraftforge/event/entity/living/LivingExperienceDropEvent;)V
java.lang.NullPointerException
	at onelemonyboi.miniutilities.items.enchantments.ExperienceHarvesterHandler.handleEntityKill(ExperienceHarvesterHandler.java:15)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.event.ForgeEventFactory.getExperienceDrop(ForgeEventFactory.java:234)
	at net.minecraft.entity.LivingEntity.func_226294_cV_(LivingEntity.java:1260)
	at net.minecraft.entity.LivingEntity.func_213345_d(LivingEntity.java:1246)
	at net.minecraft.entity.player.ServerPlayerEntity.func_70645_a(ServerPlayerEntity.java:514)
	at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:1059)
	at net.minecraft.entity.player.PlayerEntity.func_70097_a(PlayerEntity.java:814)
	at net.minecraft.entity.player.ServerPlayerEntity.func_70097_a(ServerPlayerEntity.java:597)
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_213868_a(AbstractArrowEntity.java:326)
	at net.minecraft.entity.projectile.ProjectileEntity.func_70227_a(SourceFile:118)
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_70071_h_(AbstractArrowEntity.java:188)
	at net.minecraft.entity.projectile.ArrowEntity.func_70071_h_(SourceFile:103)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611)
	at net.minecraft.world.World.func_217390_a(World.java:554)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at java.lang.Thread.run(Unknown Source)

[13may2021 23:04:45.674] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] You died, you can use /back to teleport you to your death place
[13may2021 23:04:45.682] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] jahirtrap ha muerto por un flechazo de Esqueleto glacial
[13may2021 23:04:45.685] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 79810fbb-9f60-4516-9df4-e244e6a0fc21
[13may2021 23:04:45.694] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NullPointerException
	at onelemonyboi.miniutilities.items.enchantments.ExperienceHarvesterHandler.handleEntityKill(ExperienceHarvesterHandler.java:15) ~[miniutilities:1.1.1]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.event.ForgeEventFactory.getExperienceDrop(ForgeEventFactory.java:234) ~[forge:?]
	at net.minecraft.entity.LivingEntity.func_226294_cV_(LivingEntity.java:1260) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_213345_d(LivingEntity.java:1246) ~[?:?]
	at net.minecraft.entity.player.ServerPlayerEntity.func_70645_a(ServerPlayerEntity.java:514) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:1059) ~[?:?]
	at net.minecraft.entity.player.PlayerEntity.func_70097_a(PlayerEntity.java:814) ~[?:?]
	at net.minecraft.entity.player.ServerPlayerEntity.func_70097_a(ServerPlayerEntity.java:597) ~[?:?]
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_213868_a(AbstractArrowEntity.java:326) ~[?:?]
	at net.minecraft.entity.projectile.ProjectileEntity.func_70227_a(SourceFile:118) ~[?:?]
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_70071_h_(AbstractArrowEntity.java:188) ~[?:?]
	at net.minecraft.entity.projectile.ArrowEntity.func_70071_h_(SourceFile:103) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	... 5 more

**Comment by jahirtrap** [comment]
that's the logs of my modpack.

**Comment by OneLemonyBoi** [comment]
The issue is on my end, I need to check if the player attacking is null

**Comment by OneLemonyBoi** [comment]
fixed
